version: '3'
services:
  db:
    hostname: primary
    volumes:
       - ~/pgdata-grundstuecksinformation:/pgdata:delegated
    restart: always
  client:
    image: sogis/grundstuecksinformation-client:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8181:8080"
    restart: always    
