version: '3'
services:
  client:
    image: sogis/grundstuecksinformation-client:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8181:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
  opensearch:
    depends_on:
      - client
    image: sogis/grundstuecksinformation-opensearch:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8282:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
  proxy:
    image: sogis/grundstuecksinformation-proxy:latest
    restart: always
    ports:
      - "80:80"
