version: '3'
services:
  db:
    hostname: primary
    image: sogis/oereb-db:latest
    environment:
      PG_DATABASE: grundstuecksinformation
      PG_LOCALE: de_CH.UTF-8
      PG_PRIMARY_PORT: 5432
      PG_MODE: primary
      PG_USER: admin
      PG_PASSWORD: admin
      PG_PRIMARY_USER: repl
      PG_PRIMARY_PASSWORD: repl
      PG_ROOT_PASSWORD: secret
      PG_WRITE_USER: gretl
      PG_WRITE_PASSWORD: gretl
      PG_READ_USER: ogc_server
      PG_READ_PASSWORD: ogc_server
    ports:
      - "54321:5432"
    volumes:
       - /pgdata:/pgdata
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536M
        reservations:
          cpus: '1'
          memory: 1024M
  client:
    depends_on:
      - db
    image: sogis/grundstuecksinformation-client:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8181:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
  opensearch:
    depends_on:
      - client
    image: sogis/grundstuecksinformation-opensearch:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8282:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
  embed:
    image: sogis/wgc-embedded:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8383:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
  proxy:
    image: sogis/grundstuecksinformation-proxy:latest
    restart: always
    ports:
      - "80:80"
