version: '3'
services:
  client:
    image: sogis/grundstuecksinformation-client:latest
    environment:
      SERVER_PORT: 8080
    ports:
      - "8181:8080"
    restart: always    
  proxy:
    image: sogis/grundstuecksinformation-proxy:latest
    restart: always
    ports:
      - "80:80"
